# Generated by Django 3.1.5 on 2021-04-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_userregisterform_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisterform',
            old_name='place_of_residence',
            new_name='place_of_birth',
        ),
    ]
