# Generated by Django 3.1.5 on 2021-04-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0003_auto_20210401_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisterform',
            old_name='current_living_place',
            new_name='current_residence',
        ),
    ]
